Завершение ДЗ№1
Dant777/GB_ASP.NET_APP pull request #1
Opened 2021-06-20 07:32 UTC by Dant777

2021-06-24 14:06 UTC, vladimir-shmidt reviewed
хорошая работа
правильное разделение ответственности между классами
в целом суть асинков уловил

2021-06-24 14:06 UTC, vladimir-shmidt commented on ASP.NET_APP/Helpers/BlogWorker.cs
> +            var taskEnum = requesrUriCollection.Select(r => Task.Run(() => GetOneBlogInfoAsync(r)));
можно объединить с предыдущей строкой

2021-06-24 14:06 UTC, vladimir-shmidt commented on ASP.NET_APP/Helpers/Logger.cs
> +        public static void WriteInFile(string[] strCollection)
в файл также пишется с прерыванием значит можно писать асинхронно

2021-06-24 14:06 UTC, vladimir-shmidt commented on ASP.NET_APP/Program.cs
> +            Logger.WriteInFile(blogInfoCollectiion);
что будет если в посте с id=5 случится ошибка при заказчке?

2021-06-24 14:06 UTC, vladimir-shmidt requested changes
коммент раньше оставил

2021-06-24 18:09 UTC, Dant777 commented on ASP.NET_APP/Program.cs
> +            Logger.WriteInFile(blogInfoCollectiion);
Как это проверить?

2021-06-24 18:16 UTC, vladimir-shmidt commented on ASP.NET_APP/Program.cs
> +            Logger.WriteInFile(blogInfoCollectiion);
поставь вместо номер 5 например -1

2021-06-24 18:43 UTC, Dant777 commented on ASP.NET_APP/Program.cs
> +            Logger.WriteInFile(blogInfoCollectiion);
При появлении id:-1 и id:0 в консоль выводится ошибка `Message :Response status code does not indicate success: 404 (Not Found).` т.к.  в методе `GetOneBlogInfoAsync `есть обработчик исключений который выводит ошибку в консоль, можно перенаправить ошибку в тот же логгер.

2021-06-24 18:52 UTC, Dant777 commented on ASP.NET_APP/Helpers/Logger.cs
> +        public static void WriteInFile(string[] strCollection)
Добавил метод `WriteInFileAsync`

2021-06-24 18:53 UTC, Dant777 commented on ASP.NET_APP/Helpers/BlogWorker.cs
> +            var taskEnum = requesrUriCollection.Select(r => Task.Run(() => GetOneBlogInfoAsync(r)));
Объединил

2021-06-24 18:58 UTC, vladimir-shmidt requested changes
не работает когда есть ошибки в запросах - файл не пишется

2021-06-24 18:58 UTC, vladimir-shmidt commented on ASP.NET_APP/Helpers/BlogWorker.cs
> +            var taskEnum = requesrUriCollection.Select(r => Task.Run(() => GetOneBlogInfoAsync(r)));
`r => Task.Run(() => GetOneBlogInfoAsync(r)) ` сгенерится синхронный вызов 
для лямбд нужно также указывать async await

2021-06-24 19:17 UTC, Dant777 commented
> не работает когда есть ошибки в запросах - файл не пишется

Не знаю что сказать, но файл записывается даже с маcсовыми отрицательными id

2021-07-05 14:27 UTC, vladimir-shmidt approved these changes
задание ОК

2021-07-05 14:27 UTC, vladimir-shmidt commented on ASP.NET_APP/Helpers/BlogWorker.cs
> +                .Select(r => Task.Run(() => GetOneBlogInfoAsync(r)));
нет необходимости все оборачиватьв таски

2021-07-05 14:27 UTC, vladimir-shmidt commented on ASP.NET_APP/Helpers/Logger.cs
> +                await Task.Run(() =>
таски здесь лишние

2021-07-10 08:15 UTC, merged